<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>images\Tetris.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Company>Radish</Company>
    <Product>Tetris</Product>
    <Copyright>© 2026 Radish</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="audio\clear.wav" />
    <None Remove="audio\gameover.wav" />
    <None Remove="audio\land.wav" />
    <None Remove="audio\move.wav" />
    <None Remove="audio\rotate.wav" />
    <None Remove="images\Block-Empty.png" />
    <None Remove="images\Block-I.png" />
    <None Remove="images\Block-J.png" />
    <None Remove="images\Block-L.png" />
    <None Remove="images\Block-O.png" />
    <None Remove="images\Block-S.png" />
    <None Remove="images\Block-T.png" />
    <None Remove="images\Block-Z.png" />
    <None Remove="images\GhostBlue.png" />
    <None Remove="images\GhostBlue1.png" />
    <None Remove="images\GhostCyan.png" />
    <None Remove="images\GhostCyan1.png" />
    <None Remove="images\GhostEmpty.png" />
    <None Remove="images\GhostGreen.png" />
    <None Remove="images\GhostGreen1.png" />
    <None Remove="images\GhostOrange.png" />
    <None Remove="images\GhostOrange1.png" />
    <None Remove="images\GhostPurple.png" />
    <None Remove="images\GhostPurple1.png" />
    <None Remove="images\GhostRed.png" />
    <None Remove="images\GhostRed1.png" />
    <None Remove="images\GhostYellow.png" />
    <None Remove="images\GhostYellow1.png" />
    <None Remove="images\TileBlue.png" />
    <None Remove="images\TileCyan.png" />
    <None Remove="images\TileEmpty.png" />
    <None Remove="images\TileGreen.png" />
    <None Remove="images\TileOrange.png" />
    <None Remove="images\TilePurple.png" />
    <None Remove="images\TileRed.png" />
    <None Remove="images\TileWhite.png" />
    <None Remove="images\TileYellow.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\Tetris.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="audio\clear.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="audio\gameover.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="audio\land.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="audio\move.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="audio\rotate.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-Empty.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-I.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-J.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-L.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-O.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-S.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-T.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Block-Z.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostBlue.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostBlue1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostCyan.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostCyan1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostEmpty.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostGreen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostGreen1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostOrange.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostOrange1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostPurple.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostPurple1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostRed.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostRed1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostYellow.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\GhostYellow1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileBlue.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileCyan.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileEmpty.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileGreen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileOrange.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TilePurple.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileRed.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileWhite.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\TileYellow.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
